rem rename all the episodes
ren "Looney Tunes Golden Collection Disc 1 T01*" "Looney Tunes - S1946E02 - Baseball Bugs.*"
ren "Looney Tunes Golden Collection Disc 1 T02*" "Looney Tunes - S1952E23 - Rabbit Seasoning.*"
ren "Looney Tunes Golden Collection Disc 1 T03*" "Looney Tunes - S1949E16 - Long-Haired Hare.*"
ren "Looney Tunes Golden Collection Disc 1 T04*" "Looney Tunes - S1949E11 - High Diving Hare.*"
ren "Looney Tunes Golden Collection Disc 1 T05*" "Looney Tunes - S1953E19 - Bully for Bugs.*"
ren "Looney Tunes Golden Collection Disc 1 T06*" "Looney Tunes - S1950E15 - What's Up Doc_.*"
ren "Looney Tunes Golden Collection Disc 1 T07*" "Looney Tunes - S1952E27 - Rabbit's Kin.*"
ren "Looney Tunes Golden Collection Disc 1 T08*" "Looney Tunes - S1952E11 - Water, Water Every Hare.*"
ren "Looney Tunes Golden Collection Disc 1 T09*" "Looney Tunes - S1950E10 - Big House Bunny.*"
ren "Looney Tunes Golden Collection Disc 1 T10*" "Looney Tunes - S1951E27 - Big Top Bunny.*"
ren "Looney Tunes Golden Collection Disc 1 T11*" "Looney Tunes - S1948E32 - My Bunny Lies over the Sea.*"
ren "Looney Tunes Golden Collection Disc 1 T12*" "Looney Tunes - S1941E40 - Wabbit Twouble.*"
ren "Looney Tunes Golden Collection Disc 1 T13*" "Looney Tunes - S1951E23 - Ballot Box Bunny.*"
ren "Looney Tunes Golden Collection Disc 1 T14*" "Looney Tunes - S1950E30 - Rabbit of Seville.*"
ren "Looney Tunes Golden Collection Disc 2 T01*" "Looney Tunes - S1953E06 - Duck Amuck.*"
ren "Looney Tunes Golden Collection Disc 2 T02*" "Looney Tunes - S1949E23 - Dough for the Do-Do.*"
ren "Looney Tunes Golden Collection Disc 2 T03*" "Looney Tunes - S1951E26 - Drip-Along Daffy.*"
ren "Looney Tunes Golden Collection Disc 2 T04*" "Looney Tunes - S1948E33 - Scaredy Cat.*"
ren "Looney Tunes Golden Collection Disc 2 T05*" "Looney Tunes - S1950E21 - The Ducksters.*"
ren "Looney Tunes Golden Collection Disc 2 T06*" "Looney Tunes - S1950E06 - The Scarlet Pumpernickel.*"
ren "Looney Tunes Golden Collection Disc 2 T07*" "Looney Tunes - S1943E14 - Yankee Doodle Daffy.*"
ren "Looney Tunes Golden Collection Disc 2 T08*" "Looney Tunes - S1949E05 - Porky Chops.*"
ren "Looney Tunes Golden Collection Disc 2 T09*" "Looney Tunes - S1951E17 - The Wearing of the Grin.*"
ren "Looney Tunes Golden Collection Disc 2 T10*" "Looney Tunes - S1956E23 - Deduce, You Say.*"
ren "Looney Tunes Golden Collection Disc 2 T11*" "Looney Tunes - S1950E03 - Boobs in the Woods.*"
ren "Looney Tunes Golden Collection Disc 2 T12*" "Looney Tunes - S1950E18 - Golden Yeggs.*"
ren "Looney Tunes Golden Collection Disc 2 T13*" "Looney Tunes - S1951E13 - Rabbit Fire.*"
ren "Looney Tunes Golden Collection Disc 2 T14*" "Looney Tunes - S1953E18 - Duck Dodgers in the 24th Century.*"
ren "Looney Tunes Golden Collection Disc 3 T01*" "Looney Tunes - S1940E07 - Elmer's Candid Camera.*"
ren "Looney Tunes Golden Collection Disc 3 T02*" "Looney Tunes - S1944E05 - Bugs Bunny and the Three Bears.*"
ren "Looney Tunes Golden Collection Disc 3 T03*" "Looney Tunes - S1949E24 - Fast and Furry-ous.*"
ren "Looney Tunes Golden Collection Disc 3 T04*" "Looney Tunes - S1946E10 - Hair-Raising Hare.*"
ren "Looney Tunes Golden Collection Disc 3 T05*" "Looney Tunes - S1949E04 - Awful Orphan.*"
ren "Looney Tunes Golden Collection Disc 3 T06*" "Looney Tunes - S1948E19 - Haredevil Hare.*"
ren "Looney Tunes Golden Collection Disc 3 T07*" "Looney Tunes - S1949E29 - For Scent-imental Reasons.*"
ren "Looney Tunes Golden Collection Disc 3 T08*" "Looney Tunes - S1949E26 - Frigid Hare.*"
ren "Looney Tunes Golden Collection Disc 3 T09*" "Looney Tunes - S1950E09 - The Hypo-Chondri-Cat.*"
ren "Looney Tunes Golden Collection Disc 3 T10*" "Looney Tunes - S1959E01 - Baton Bunny.*"
ren "Looney Tunes Golden Collection Disc 3 T11*" "Looney Tunes - S1952E03 - Feed the Kitty.*"
ren "Looney Tunes Golden Collection Disc 3 T12*" "Looney Tunes - S1953E01 - Don't Give Up the Sheep.*"
ren "Looney Tunes Golden Collection Disc 3 T13*" "Looney Tunes - S1942E22 - Bugs Bunny Gets the Boid.*"
ren "Looney Tunes Golden Collection Disc 3 T14*" "Looney Tunes - S1943E04 - Tortoise Wins by a Hare.*"
ren "Looney Tunes Golden Collection Disc 4 T01*" "Looney Tunes - S1950E24 - Canary Row.*"
ren "Looney Tunes Golden Collection Disc 4 T02*" "Looney Tunes - S1950E23 - Bunker Hill Bunny.*"
ren "Looney Tunes Golden Collection Disc 4 T03*" "Looney Tunes - S1948E29 - Kit for Cat.*"
ren "Looney Tunes Golden Collection Disc 4 T04*" "Looney Tunes - S1951E05 - Putty Tat Trouble.*"
ren "Looney Tunes Golden Collection Disc 4 T05*" "Looney Tunes - S1954E07 - Bugs and Thugs.*"
ren "Looney Tunes Golden Collection Disc 4 T06*" "Looney Tunes - S1951E03 - Canned Feud.*"
ren "Looney Tunes Golden Collection Disc 4 T07*" "Looney Tunes - S1955E16 - Lumber Jerks.*"
ren "Looney Tunes Golden Collection Disc 4 T08*" "Looney Tunes - S1955E23 - Speedy Gonzales.*"
ren "Looney Tunes Golden Collection Disc 4 T09*" "Looney Tunes - S1951E22 - Tweety's S.O.S..*"
ren "Looney Tunes Golden Collection Disc 4 T10*" "Looney Tunes - S1948E26 - The Foghorn Leghorn.*"
ren "Looney Tunes Golden Collection Disc 4 T11*" "Looney Tunes - S1949E08 - Daffy Duck Hunt.*"
ren "Looney Tunes Golden Collection Disc 4 T12*" "Looney Tunes - S1951E12 - Early to Bet.*"
ren "Looney Tunes Golden Collection Disc 4 T13*" "Looney Tunes - S1959E18 - A Broken Leghorn.*"
ren "Looney Tunes Golden Collection Disc 4 T14*" "Looney Tunes - S1954E15 - Devil May Hare.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T01*" "Looney Tunes - S1946E21 - The Big Snooze.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T02*" "Looney Tunes - S1956E05 - Broom-Stick Bunny.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T03*" "Looney Tunes - S1948E15 - Bugs Bunny Rides Again.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T04*" "Looney Tunes - S1951E07 - Bunny Hugged.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T05*" "Looney Tunes - S1951E16 - French Rarebit.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T06*" "Looney Tunes - S1948E01 - Gorilla My Dreams.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T07*" "Looney Tunes - S1942E35 - The Hare-Brained Hypnotist.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T08*" "Looney Tunes - S1945E13 - Hare Conditioned.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T09*" "Looney Tunes - S1941E23 - The Heckling Hare.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T10*" "Looney Tunes - S1944E01 - Little Red Riding Rabbit.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T11*" "Looney Tunes - S1941E09 - Tortoise Beats Hare.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T12*" "Looney Tunes - S1947E08 - Rabbit Transit.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T13*" "Looney Tunes - S1947E19 - Slick Hare.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T14*" "Looney Tunes - S1954E30 - Baby Buggy Bunny.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T15*" "Looney Tunes - S1955E21 - Hyde and Hare.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T01*" "Looney Tunes - S1952E08 - Beep Beep.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T02*" "Looney Tunes - S1952E12 - Going! Going! Gosh!.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T03*" "Looney Tunes - S1953E23 - Zipping Along.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T04*" "Looney Tunes - S1954E20 - Stop! Look! and Hasten!.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T05*" "Looney Tunes - S1955E11 - Ready.. Set.. Zoom!.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T06*" "Looney Tunes - S1955E29 - Guided Muscle.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T07*" "Looney Tunes - S1956E11 - Gee Whiz-z-z-z-z-z-z.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T08*" "Looney Tunes - S1956E26 - There They GO-GO-GO!.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T09*" "Looney Tunes - S1957E03 - Scrambled Aches.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T10*" "Looney Tunes - S1957E19 - Zoom and Bored.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T11*" "Looney Tunes - S1958E07 - Whoa, Be-Gone!.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T12*" "Looney Tunes - S1951E20 - Cheese Chasers.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T13*" "Looney Tunes - S1942E31 - The Dover Boys.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T14*" "Looney Tunes - S1949E10 - Mouse Wreckers.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T15*" "Looney Tunes - S1951E24 - A Bear for Punishment.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T01*" "Looney Tunes - S1949E19 - Bad Ol' Putty Tat.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T02*" "Looney Tunes - S1950E16 - All A Bir-r-r-d.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T03*" "Looney Tunes - S1951E14 - Room and Bird.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T04*" "Looney Tunes - S1951E28 - Tweet Tweet Tweety.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T05*" "Looney Tunes - S1952E04 - Gift Wrapped.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T06*" "Looney Tunes - S1952E16 - Ain't She Tweet.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T07*" "Looney Tunes - S1952E21 - A Bird in a Guilty Cage.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T08*" "Looney Tunes - S1953E02 - Snow Business.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T09*" "Looney Tunes - S1947E07 - Tweetie Pie.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T10*" "Looney Tunes - S1946E11 - Kitty Kornered.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T11*" "Looney Tunes - S1946E05 - Baby Bottleneck.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T12*" "Looney Tunes - S1939E22 - Old Glory.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T13*" "Looney Tunes - S1946E15 - The Great Piggy Bank Robbery.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T14*" "Looney Tunes - S1944E12 - Duck Soup to Nuts.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T15*" "Looney Tunes - S1938E29 - Porky in Wackyland.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T01*" "Looney Tunes - S1948E08 - Back Alley Oproar.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T02*" "Looney Tunes - S1946E01 - Book Revue.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T03*" "Looney Tunes - S1943E22 - A Corny Concerto.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T04*" "Looney Tunes - S1938E19 - Have You Got Any Castles_.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T05*" "Looney Tunes - S1941E17 - Hollywood Steps Out.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T06*" "Looney Tunes - S1936E19 - I Love to Singa.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T07*" "Looney Tunes - S1938E17 - Katnip Kollege.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T08*" "Looney Tunes - S1942E32 - The Hep Cat.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T09*" "Looney Tunes - S1957E01 - Three Little Bops.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T10*" "Looney Tunes - S1955E31 - One Froggy Evening.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T11*" "Looney Tunes - S1946E24 - Rhapsody Rabbit.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T12*" "Looney Tunes - S1957E22 - Show Biz Bugs.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T13*" "Looney Tunes - S1944E27 - Stage Door Cartoon.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T14*" "Looney Tunes - S1957E14 - What's Opera, Doc_.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T15*" "Looney Tunes - S1940E16 - You Ought to Be in Pictures.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T01*" "Looney Tunes - S1944E17 - Hare Force.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T02*" "Looney Tunes - S1946E06 - Hare Remover.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T03*" "Looney Tunes - S1945E17 - Hare Tonic.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T04*" "Looney Tunes - S1947E05 - A Hare Grows in Manhattan.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T05*" "Looney Tunes - S1947E12 - Easter Yeggs.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T06*" "Looney Tunes - S1942E09 - The Wabbit Who Came to Supper.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T07*" "Looney Tunes - S1949E14 - Bowery Bugs.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T08*" "Looney Tunes - S1950E07 - Homeless Hare.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T09*" "Looney Tunes - S1942E39 - Case of the Missing Hare.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T10*" "Looney Tunes - S1946E13 - Acrobatty Bunny.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T11*" "Looney Tunes - S1943E17 - Wackiki Wabbit.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T12*" "Looney Tunes - S1949E02 - Hare Do.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T13*" "Looney Tunes - S1949E09 - Rebel Rabbit.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T14*" "Looney Tunes - S1950E19 - Hillbilly Hare.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T15*" "Looney Tunes - S1953E24 - Duck! Rabbit, Duck!.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T01*" "Looney Tunes - S1938E37 - Daffy Duck in Hollywood.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T02*" "Looney Tunes - S1935E20 - Hollywood Capers.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T03*" "Looney Tunes - S1936E30 - The CooCoo Nut Grove.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T04*" "Looney Tunes - S1937E04 - Porky's Road Race.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T05*" "Looney Tunes - S1937E34 - The Woods Are Full of Cuckoos.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T06*" "Looney Tunes - S1937E09 - She Was an Acrobat's Daughter.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T07*" "Looney Tunes - S1939E43 - The Film Fan.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T08*" "Looney Tunes - S1937E25 - Speaking of the Weather.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T09*" "Looney Tunes - S1939E15 - Thugs with Dirty Mugs.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T10*" "Looney Tunes - S1941E11 - Goofy Groceries.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T11*" "Looney Tunes - S1944E10 - Swooner Crooner.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T12*" "Looney Tunes - S1956E25 - Wideo Wabbit.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T13*" "Looney Tunes - S1956E28 - The Honey-Mousers.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T14*" "Looney Tunes - S1961E18 - The Last Hungry Cat.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T15*" "Looney Tunes - S1959E06 - The Mouse That Jack Built.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T01*" "Looney Tunes - S1935E04 - I Haven't Got a Hat.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T02*" "Looney Tunes - S1937E08 - Porky's Romance.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T03*" "Looney Tunes - S1938E18 - Porky's Party.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T04*" "Looney Tunes - S1938E33 - Porky in Egypt.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T05*" "Looney Tunes - S1939E14 - Porky and Teabiscuit.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T06*" "Looney Tunes - S1937E03 - Pigs Is Pigs.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T07*" "Looney Tunes - S1943E03 - Pigs in a Polka.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T08*" "Looney Tunes - S1943E18 - Porky Pig's Feat.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T09*" "Looney Tunes - S1948E06 - Daffy Duck Slept Here.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T10*" "Looney Tunes - S1949E28 - Bye, Bye Bluebeard.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T11*" "Looney Tunes - S1950E13 - An Egg Scramble.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T12*" "Looney Tunes - S1958E05 - Robin Hood Daffy.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T13*" "Looney Tunes - S1949E22 - The Windblown Hare.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T14*" "Looney Tunes - S1954E13 - Claws For Alarm.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T15*" "Looney Tunes - S1956E06 - Rocket Squad.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T01*" "Looney Tunes - S1939E13 - Daffy Duck and the Dinosaur.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T02*" "Looney Tunes - S1943E09 - Super-Rabbit.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T03*" "Looney Tunes - S1938E01 - Daffy Duck & Egghead.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T04*" "Looney Tunes - S1945E10 - A Gruesome Twosome.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T05*" "Looney Tunes - S1945E03 - Draftee Daffy.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T06*" "Looney Tunes - S1943E24 - Falling Hare.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T07*" "Looney Tunes - S1957E12 - Steal Wool.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T08*" "Looney Tunes - S1957E16 - Birds Anonymous.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T09*" "Looney Tunes - S1954E06 - No Barking.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T10*" "Looney Tunes - S1948E10 - Rabbit Punch.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T11*" "Looney Tunes - S1943E27 - An Itch in Time.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T12*" "Looney Tunes - S1945E01 - Odor-Able Kitty.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T13*" "Looney Tunes - S1946E18 - Walky Talky Hawky.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T14*" "Looney Tunes - S1957E24 - Gonzales' Tamales.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T15*" "Looney Tunes - S1963E17 - To Beep or Not to Beep.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T01*" "Looney Tunes - S1955E27 - Roman Legion-Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T02*" "Looney Tunes - S1949E20 - The Grey Hounded Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T03*" "Looney Tunes - S1949E34 - Rabbit Hood.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T04*" "Looney Tunes - S1952E02 - Operation_ Rabbit.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T05*" "Looney Tunes - S1955E24 - Knight-Mare Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T06*" "Looney Tunes - S1953E11 - Southern Fried Rabbit.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T07*" "Looney Tunes - S1949E06 - Mississippi Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T08*" "Looney Tunes - S1950E02 - Hurdy-Gurdy Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T09*" "Looney Tunes - S1953E04 - Forward March Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T10*" "Looney Tunes - S1955E08 - Sahara Hare.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T11*" "Looney Tunes - S1956E17 - Barbary-Coast Bunny.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T12*" "Looney Tunes - S1956E29 - To Hare is Human.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T13*" "Looney Tunes - S1950E14 - 8 Ball Bunny.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T14*" "Looney Tunes - S1958E13 - Knighty Knight Bugs.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T15*" "Looney Tunes - S1957E25 - Rabbit Romeo.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T01*" "Looney Tunes - S1937E31 - The Case of the Stuttering Pig.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T02*" "Looney Tunes - S1938E30 - Little Pancho Vanilla.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T03*" "Looney Tunes - S1936E29 - Little Beau Porky.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T04*" "Looney Tunes - S1938E13 - Now That Summer Is Gone.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T05*" "Looney Tunes - S1936E32 - Porky in the North Woods.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T06*" "Looney Tunes - S1938E34 - You're an Education.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T07*" "Looney Tunes - S1937E22 - Porky's Railroad.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T08*" "Looney Tunes - S1944E22 - Plane Daffy.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T09*" "Looney Tunes - S1938E16 - Porky the Fireman.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T10*" "Looney Tunes - S1938E27 - Cracked Ice.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T11*" "Looney Tunes - S1943E28 - Puss N' Booty.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T12*" "Looney Tunes - S1944E06 - I Got Plenty of Mutton.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T13*" "Looney Tunes - S1944E24 - Booby Hatched.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T14*" "Looney Tunes - S1936E22 - Porky's Poultry Plant.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T15*" "Looney Tunes - S1944E26 - The Stupid Cupid.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T01*" "Looney Tunes - S1953E21 - Cat-Tails For Two.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T02*" "Looney Tunes - S1957E15 - Tabasco Road.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T03*" "Looney Tunes - S1958E02 - Tortilla Flaps.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T04*" "Looney Tunes - S1959E12 - Mexicali Shmoes.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T05*" "Looney Tunes - S1959E16 - Here Today, Gone Tamale.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T06*" "Looney Tunes - S1960E02 - West of the Pesos.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T07*" "Looney Tunes - S1961E01 - Cannery Woe.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T08*" "Looney Tunes - S1961E13 - The Pied Piper of Guadalupe.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T09*" "Looney Tunes - S1962E06 - Mexican Boarders.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T10*" "Looney Tunes - S1963E11 - Chili Weather.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T11*" "Looney Tunes - S1964E02 - A Message To Gracias.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T12*" "Looney Tunes - S1964E06 - Nuts and Volts.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T13*" "Looney Tunes - S1964E12 - Pancho's Hideaway.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T14*" "Looney Tunes - S1965E05 - The Wild Chase.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T15*" "Looney Tunes - S1966E09 - A-Haunting We Will Go.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T01*" "Looney Tunes - S1938E35 - The Night Watchman.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T02*" "Looney Tunes - S1942E07 - Conrad the Sailor.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T03*" "Looney Tunes - S1940E34 - The Sour Puss.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T04*" "Looney Tunes - S1943E16 - The Aristo-Cat.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T05*" "Looney Tunes - S1948E21 - Dough Ray Me-ow.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T06*" "Looney Tunes - S1955E01 - Pizzicato Pussycat.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T07*" "Looney Tunes - S1953E05 - Kiss Me Cat.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T08*" "Looney Tunes - S1958E20 - Cat Feud.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T09*" "Looney Tunes - S1956E13 - The Unexpected Pest.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T10*" "Looney Tunes - S1957E05 - Go Fly a Kit.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T11*" "Looney Tunes - S1952E10 - Kiddin' the Kitten.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T12*" "Looney Tunes - S1953E08 - A Peck O' Trouble.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T13*" "Looney Tunes - S1960E11 - Mouse and Garden.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T14*" "Looney Tunes - S1940E13 - Porky's Poor Fish.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T15*" "Looney Tunes - S1949E27 - Swallow the Leader.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T01*" "Looney Tunes - S1952E07 - 14 Carrot Rabbit.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T02*" "Looney Tunes - S1957E04 - Ali Baba Bunny.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T03*" "Looney Tunes - S1948E13 - Buccaneer Bunny.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T04*" "Looney Tunes - S1956E01 - Bugs' Bonnets.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T05*" "Looney Tunes - S1956E22 - A Star is Bored.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T06*" "Looney Tunes - S1947E14 - A Pest in the House.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T07*" "Looney Tunes - S1963E16 - Transylvania 6-5000.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T08*" "Looney Tunes - S1952E17 - Oily Hare.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T09*" "Looney Tunes - S1956E16 - Stupor Duck.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T10*" "Looney Tunes - S1948E30 - The Stupor Salesman.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T11*" "Looney Tunes - S1961E08 - The Abominable Snow Rabbit.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T12*" "Looney Tunes - S1952E26 - The Super Snooper.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T13*" "Looney Tunes - S1948E17 - The Up-Standing Sitter.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T14*" "Looney Tunes - S1946E12 - Hollywood Daffy.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T15*" "Looney Tunes - S1948E20 - You Were Never Duckier.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T01*" "Looney Tunes - S1954E18 - Bewitched Bunny.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T02*" "Looney Tunes - S1949E07 - Paying the Piper.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T03*" "Looney Tunes - S1940E11 - The Bear's Tale.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T04*" "Looney Tunes - S1942E24 - Foney Fables.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T05*" "Looney Tunes - S1960E05 - Goldimouse and the Three Cats.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T06*" "Looney Tunes - S1946E03 - Holiday for Shoestrings.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T07*" "Looney Tunes - S1952E13 - Little Red Rodent Hood.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T08*" "Looney Tunes - S1937E32 - Little Red Walking Hood.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T09*" "Looney Tunes - S1955E26 - Red Riding Hoodwinked.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T10*" "Looney Tunes - S1941E14 - The Trial of Mr. Wolf.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T11*" "Looney Tunes - S1952E18 - The Turn-Tale Wolf.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T12*" "Looney Tunes - S1940E18 - Tom Thumb in Trouble.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T13*" "Looney Tunes - S1957E10 - Tweety and the Beanstalk.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T14*" "Looney Tunes - S1940E17 - A Gander at Mother Goose.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T15*" "Looney Tunes - S1964E11 - Senorella And The Glass Huarache.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T01*" "Looney Tunes - S1946E16 - Bacall to Arms.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T02*" "Looney Tunes - S1944E20 - Buckaroo Bugs.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T03*" "Looney Tunes - S1942E08 - Crazy Cruise.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T04*" "Looney Tunes - S1941E16 - Farm Frolics.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T05*" "Looney Tunes - S1944E15 - Hare Ribbin'.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T06*" "Looney Tunes - S1940E26 - Patient Porky.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T07*" "Looney Tunes - S1940E31 - Prehistoric Porky.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T08*" "Looney Tunes - S1945E15 - The Bashful Buzzard.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T09*" "Looney Tunes - S1944E25 - The Old Grey Hare.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T10*" "Looney Tunes - S1942E14 - The Wacky Wabbit.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T11*" "Looney Tunes - S1943E11 - The Wise Quacking Duck.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T12*" "Looney Tunes - S1945E12 - Wagon Heels.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T13*" "Looney Tunes - S1938E36 - The Daffy Doc.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T14*" "Looney Tunes - S1942E36 - A Tale of Two Kitties.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T15*" "Looney Tunes - S1941E41 - Porky's Pooch.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T01*" "Looney Tunes - S1936E06 - Alpine Antics.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T02*" "Looney Tunes - S1942E28 - Eatin' on the Cuff or The Moth Who Came to Dinner.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T03*" "Looney Tunes - S1936E26 - Milk and Money.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T04*" "Looney Tunes - S1933E19 - I've Got to Sing a Torch Song.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T05*" "Looney Tunes - S1938E04 - Porky at the Crocadero.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T06*" "Looney Tunes - S1939E19 - Polar Pals.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T07*" "Looney Tunes - S1943E20 - Scrap Happy Daffy.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T08*" "Looney Tunes - S1937E33 - Porky's Double Trouble.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T09*" "Looney Tunes - S1935E21 - Gold Diggers of '49.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T10*" "Looney Tunes - S1940E08 - Pilgrim Porky.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T11*" "Looney Tunes - S1939E26 - Wise Quacks.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T12*" "Looney Tunes - S1941E13 - Porky's Preview.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T13*" "Looney Tunes - S1938E02 - Porky's Poppa.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T14*" "Looney Tunes - S1938E25 - Wholly Smoke.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T15*" "Looney Tunes - S1938E06 - What Price Porky.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T01*" "Looney Tunes - S1945E08 - Hare Trigger.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T02*" "Looney Tunes - S1943E05 - To Duck or Not to Duck.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T03*" "Looney Tunes - S1947E06 - Birth of a Notion.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T04*" "Looney Tunes - S1954E28 - My Little Duckaroo.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T05*" "Looney Tunes - S1947E13 - Crowing Pains.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T06*" "Looney Tunes - S1956E20 - Raw! Raw! Rooster.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T07*" "Looney Tunes - S1956E08 - Heaven Scent.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T08*" "Looney Tunes - S1942E38 - My Favorite Duck.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T09*" "Looney Tunes - S1955E19 - Jumpin' Jupiter.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T10*" "Looney Tunes - S1954E19 - Satan's Waitin'.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T11*" "Looney Tunes - S1958E16 - Hook, Line, and Stinker.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T12*" "Looney Tunes - S1949E32 - Bear Feat.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T13*" "Looney Tunes - S1950E20 - Dog Gone South.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T14*" "Looney Tunes - S1949E33 - A Ham in a Role.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T15*" "Looney Tunes - S1949E21 - Often an Orphan.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T01*" "Looney Tunes - S1945E02 - Herr Meets Hare.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T02*" "Looney Tunes - S1944E11 - Russian Rhapsody.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T03*" "Looney Tunes - S1943E26 - Daffy- The Commando.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T04*" "Looney Tunes - S1931E12 - Bosko the Doughboy.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T05*" "Looney Tunes - S1941E35 - Rookie Revue.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T06*" "Looney Tunes - S1942E15 - The Draft Horse.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T07*" "Looney Tunes - S1942E23 - Wacky Blackout.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T08*" "Looney Tunes - S1942E25 - The Ducktators.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T09*" "Looney Tunes - S1944E07 - The Weakly Reporter.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T10*" "Looney Tunes - S1943E06 - The Fifth-Column Mouse.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T11*" "Looney Tunes - S1941E22 - Meet John Doughboy.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T12*" "Looney Tunes - S1946E08 - Hollywood Canine Canteen.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T13*" "Looney Tunes - S1954E24 - By Word of Mouse.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T14*" "Looney Tunes - S1955E28 - Heir-Conditioned.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T15*" "Looney Tunes - S1956E24 - Yankee Dood It.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T01*" "Looney Tunes - S1930E02 - Congo Jazz.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T02*" "Looney Tunes - S1931E09 - Smile, Darn Ya, Smile!.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T03*" "Looney Tunes - S1930E04 - The Booze Hangs High.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T04*" "Looney Tunes - S1931E11 - One More Time.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T05*" "Looney Tunes - S1933E16 - Bosko's Picture Show.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T06*" "Looney Tunes - S1931E13 - You Don't Know What You're Doin'!.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T07*" "Looney Tunes - S1933E15 - We're in the Money.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T08*" "Looney Tunes - S1932E20 - Ride Him, Bosko!.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T09*" "Looney Tunes - S1933E13 - Shuffle Off to Buffalo.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T10*" "Looney Tunes - S1933E04 - Bosko in Person.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T11*" "Looney Tunes - S1933E14 - The Dish Ran Away with the Spoon.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T12*" "Looney Tunes - S1933E17 - Buddy's Day Out.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T13*" "Looney Tunes - S1933E21 - Buddy's Beer Garden.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T14*" "Looney Tunes - S1934E20 - Buddy's Circus.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T15*" "Looney Tunes - S1935E18 - A Cartoonist's Nightmare.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T01*" "Looney Tunes - S1942E11 - Horton Hatches the Egg.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T02*" "Looney Tunes - S1942E16 - Lights Fantastic.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T03*" "Looney Tunes - S1945E14 - Fresh Airedale.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T04*" "Looney Tunes - S1951E15 - Chow Hound.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T05*" "Looney Tunes - S1954E17 - The Oily American.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T06*" "Looney Tunes - S1950E17 - It's Hummer Time.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T07*" "Looney Tunes - S1956E18 - Rocket-Bye Baby.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T08*" "Looney Tunes - S1954E23 - Goo Goo Goliath.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T09*" "Looney Tunes - S1954E05 - Wild Wife.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T10*" "Looney Tunes - S1953E13 - Much Ado About Nutting.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T11*" "Looney Tunes - S1955E10 - The Hole Idea.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T12*" "Looney Tunes - S1963E06 - Now Hear This.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T13*" "Looney Tunes - S1962E17 - Martian Through Georgia.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T14*" "Looney Tunes - S1936E05 - Page Miss Glory.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T15*" "Looney Tunes - S1968E02 - Norman Normal.*"

rem create all the folders we need and move the episodes into them
mkdir 1950
move /y *S1950* .\1950
mkdir 1948
move /y *S1948* .\1948
mkdir 1951
move /y *S1951* .\1951
mkdir 1954
move /y *S1954* .\1954
mkdir 1955
move /y *S1955* .\1955
mkdir 1949
move /y *S1949* .\1949
mkdir 1959
move /y *S1959* .\1959
mkdir 1953
move /y *S1953* .\1953
mkdir 1943
move /y *S1943* .\1943
mkdir 1956
move /y *S1956* .\1956
mkdir 1940
move /y *S1940* .\1940
mkdir 1944
move /y *S1944* .\1944
mkdir 1946
move /y *S1946* .\1946
mkdir 1952
move /y *S1952* .\1952
mkdir 1942
move /y *S1942* .\1942
mkdir 1945
move /y *S1945* .\1945
mkdir 1941
move /y *S1941* .\1941
mkdir 1947
move /y *S1947* .\1947
mkdir 1957
move /y *S1957* .\1957
mkdir 1958
move /y *S1958* .\1958
mkdir 1939
move /y *S1939* .\1939
mkdir 1938
move /y *S1938* .\1938
mkdir 1936
move /y *S1936* .\1936
mkdir 1935
move /y *S1935* .\1935
mkdir 1937
move /y *S1937* .\1937
mkdir 1961
move /y *S1961* .\1961
mkdir 1963
move /y *S1963* .\1963
mkdir 1960
move /y *S1960* .\1960
mkdir 1962
move /y *S1962* .\1962
mkdir 1964
move /y *S1964* .\1964
mkdir 1965
move /y *S1965* .\1965
mkdir 1966
move /y *S1966* .\1966
mkdir 1933
move /y *S1933* .\1933
mkdir 1931
move /y *S1931* .\1931
mkdir 1930
move /y *S1930* .\1930
mkdir 1932
move /y *S1932* .\1932
mkdir 1934
move /y *S1934* .\1934
mkdir 1968
move /y *S1968* .\1968

rem
rem Rename all the specials
rem

rem Volume 1
ren "Looney Tunes Golden Collection Disc 1 T15*" "Looney Tunes - S00E56 - Behind the Tunes - Bugs - A Rabbit for All Seasonings.*"
ren "Looney Tunes Golden Collection Disc 1 T16*" "Looney Tunes - S00E55 - Behind the Tunes - Short Fuse Shootout - The Small Tale of Yosemite Sam.*"
ren "Looney Tunes Golden Collection Disc 1 T17*" "Looney Tunes - S00E57 - Behind the Tunes - Forever Befuddled.*"
ren "Looney Tunes Golden Collection Disc 1 T18*" "Looney Tunes - S00E45 - The Boys from Termite Terrace-part1.*"
ren "Looney Tunes Golden Collection Disc 1 T24*" "Looney Tunes - S00E109 - My Dream Is Yours.*"
ren "Looney Tunes Golden Collection Disc 2 T15*" "Looney Tunes - SS00E54 - Behind the Tunes - Hard Luck Duck.*"
ren "Looney Tunes Golden Collection Disc 2 T16*" "Looney Tunes - S00E94 - Behind the Tunes - Porky Pig Roast - A Tribute to the World's Most Famous Ham.*"
ren "Looney Tunes Golden Collection Disc 2 T17*" "Looney Tunes - S00E62 - Behind the Tunes - Animal Quackers.*"
ren "Looney Tunes Golden Collection Disc 2 T18*" "Looney Tunes - S00E45 - The Boys from Termite Terrace-part2.*"
ren "Looney Tunes Golden Collection Disc 3 T15*" "Looney Tunes - S00E88 - Behind the Tunes - Too Fast, Too Furry-ous.*"
ren "Looney Tunes Golden Collection Disc 3 T16*" "Looney Tunes - S00E63 - Behind the Tunes - Blanc Expressions.*"
ren "Looney Tunes Golden Collection Disc 3 T17*" "Looney Tunes - S00E93 - Behind the Tunes - Merrie Melodies - Carl Stalling and Cartoon Music.*"
ren "Looney Tunes Golden Collection Disc 3 T18*" "Looney Tunes - S00E100 - A ToonHeads Special - The Lost Cartoons.*"
ren "Looney Tunes Golden Collection Disc 4 T15*" "Looney Tunes - S00E69 - Behind the Tunes - Needy for Speedy.*"
ren "Looney Tunes Golden Collection Disc 4 T16*" "Looney Tunes - S00E72 - Behind the Tunes - Putty Problems And Canary Rows.*"
ren "Looney Tunes Golden Collection Disc 4 T17*" "Looney Tunes - S00E77 - Behind the Tunes - Southern Pride Chicken.*"
ren "Looney Tunes Golden Collection Disc 4 T18*" "Looney Tunes - S00E50 - Irreverent Imagination - The Golden Age of the Looney Tunes.*"
rem Volume 2
ren "Looney Tunes Golden Collection 2 Disc 1 T19*" "Looney Tunes - S00E107 - Looney Tunes 50th Anniversary-part1.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T20*" "Looney Tunes - S00E61 - Behind the Tunes - A Conversation with Tex Avery.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T18*" "Looney Tunes - S00E84 - Adventures of the Road-Runner.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T19*" "Looney Tunes - S00E90 - Behind the Tunes - Crash Bang Boom - The Wild Sounds of Treg Brown.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T19*" "Looney Tunes - S00E107 - Looney Tunes 50th Anniversary-part2.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T22*" "Looney Tunes - S00E101 - Behind the Tunes - Man from Wackyland - The Art of Bob Clampett.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T20*" "Looney Tunes - S00E67 - Behind the Tunes - Looney Tunes Go Hollywood.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T21*" "Looney Tunes - S00E91 - Behind the Tunes - It Hopped One Night - A Look at 'One Froggy Evening'.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T22*" "Looney Tunes - S00E58 - Behind the Tunes - Wagnerian Wabbit - The Making of 'What's Opera, Doc?'.*"
rem Volume 3
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T19*" "Looney Tunes - S00E59 - Behind the Tunes - A Hunting We Will Go - Chuck Jones' Wabbit Season Twilogy.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T20*" "Looney Tunes - S00E43 - Chuck Amuck - The Movie.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T19*" "Looney Tunes - S00E115 - What's Up Doc - A Salute to Bugs Bunny-part1.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T21*" "Looney Tunes - S00E64 - Behind the Tunes - Bosko, Buddy and the Best of Black and White.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T22*" "Looney Tunes - S00E65 - Behind the Tunes - Fine Tooning - Restoring the Warner Bros Cartoons.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T19*" "Looney Tunes - S00E96 - Behind the Tunes - Tish Tash - The Animated World of Frank Tashlin.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T20*" "Looney Tunes - S00E115 - What's Up Doc - A Salute to Bugs Bunny-part2.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T19*" "Looney Tunes - S00E76 - Philbert.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T21*" "Looney Tunes - S00E68 - Behind the Tunes - Looney Tunes Go to War.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T22*" "Looney Tunes - S00E95 - Behind the Tunes - Strictly for the Birds - Tweety and Sylvester's Award-Winning Teamup.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T23*" "Looney Tunes - S00E89 - Behind the Tunes - The Charm of Stink - On the Scent of Pepe Le Pew.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T26*" "Looney Tunes - S00E06 - Spies.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T27*" "Looney Tunes - S00E11 - Rumors.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T28*" "Looney Tunes - S00E89 - Snafuperman.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T20*" "Looney Tunes - S00E97 - Behind the Tunes - Twilight in Tunes - The Music of Raymond Scott.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T23*" "Looney Tunes - S00E15 - Fifty Years of Bugs Bunny in 3_5 Minutes.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T25*" "Looney Tunes - S00E07 - The Goldbrick.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T26*" "Looney Tunes - S00E10 - The Home Front.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T27*" "Looney Tunes - S00E20 - Censored.*"
rem Volume 4
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T20*" "Looney Tunes - S00E99 - Friz on Film.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T22*" "Looney Tunes - S00E40 - 90 Day Wondering.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 3 T23*" "Looney Tunes - S00E41 - Drafty, Isn't It.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T21*" "Looney Tunes - S00E71 - Behind the Tunes - One Hit Wonders.*" 
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T22*" "Looney Tunes - S00E75 - Behind the Tunes - Sing-a-Song of Looney Tunes.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T23*" "Looney Tunes - S00E78 - Behind the Tunes - The Art of the Gag.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T24*" "Looney Tunes - S00E98 - Behind the Tunes - Wild Lines - The Art of Voice Acting.*" 
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T25*" "Looney Tunes - S00E92 - Behind the Tunes - Looney Tunes - A Cast of Thousands.*" 
rem Volume 5
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T25*" "Looney Tunes - S00E49 - Chuck Jones - Extremes and In-Betweens - A Life in Animation-part1.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T28*" "Looney Tunes - S00E44 - Chuck Jones -General Foods commercials starring Bugs and company.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T25*" "Looney Tunes - S00E49 - Chuck Jones - Extremes and In-Betweens - A Life in Animation-part2.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T26*" "Looney Tunes - S00E85 - A Chuck Jones Tutorial - Tricks of the Cartoon Trade.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T28*" "Looney Tunes - S00E70 - Behind the Tunes - Once Upon a Looney Tune.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 2 T29*" "Looney Tunes - S00E83 - Behind the Tunes - Drawn to Life - The Art of Robert McKimson.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T25*" "Looney Tunes - S00E87 - Behind the Tunes - Wacky Warner One-Shots.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T26*" "Looney Tunes - S00E80 - Behind the Tunes - Real American Zero - The Adventures of Private Snafu.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T27*" "Looney Tunes - S00E108 - Hare Ribbin' (Director's Cut).*" 
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T31*" "Looney Tunes - S00E04 - Coming Snafu.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T32*" "Looney Tunes - S00E05 - Gripes.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T34*" "Looney Tunes - S00E34 - The Good Egg.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T35*" "Looney Tunes - S00E35 - The Return of Mr Hook.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T36*" "Looney Tunes - S00E36 - Tokyo Woes.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T24*" "Looney Tunes - S00E86 - Unsung Maestros - A Directors' Tribute.*"
rem Volume 6
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T27*" "Looney Tunes - S00E01 - Crying for the Carolines.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T28*" "Looney Tunes - S00E25 - Haunted Gold Title Sequence.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T29*" "Looney Tunes - S00E28 - Schlesinger Productions Christmas Party.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T30*" "Looney Tunes - S00E46 - Mel Blanc - The Man of a Thousand Voices.*"

rem
rem Rename all undefined extras
rem
rem Volume 1
ren "Looney Tunes Golden Collection Disc 1 T19*" "Michael Barrier Commentary-other.*"
ren "Looney Tunes Golden Collection Disc 1 T22*" "A Greetings From Chuck Jones-other.*"
ren "Looney Tunes Golden Collection Disc 1 T23*" "Two Guys From Texas-featurette.*"
ren "Looney Tunes Golden Collection Disc 1 T25*" "The Bugs Bunny Show - A Star Is Bored-featurette.*"
ren "Looney Tunes Golden Collection Disc 1 T26*" "The Bugs Bunny Show - Astro Nuts-featurette.*"
ren "Looney Tunes Golden Collection Disc 1 T27*" "Blooper Bunny - Bugs Bunny 51st Anniversary-deleted.*"
ren "Looney Tunes Golden Collection Disc 3 T22*" "Hair-raising Hare Scheme-matics-behindthescenes.*"
ren "Looney Tunes Golden Collection Disc 3 T23*" "The Hypo-chondri-cat Scheme-matics-behindthescenes.*"
ren "Looney Tunes Golden Collection Disc 4 T22*" "Bosko, The Talk-ink Kid-other.*"
ren "Looney Tunes Golden Collection Disc 4 T23*" "Virgil Ross Pencil Tests-other.*"
rem Volume 2
ren "Looney Tunes Golden Collection 2 Disc 1 T21*" "The Bugs Bunny Show - Do or Diet-other.*"
ren "Looney Tunes Golden Collection 2 Disc 1 T22*" "The Bugs Bunny Show - There's No Business Like Slow Business-other.*"
ren "Looney Tunes Golden Collection 2 Disc 2 T20*" "The Bugs Bunny and Road Runner Show - Opening Sequence-other.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T20*" "Daffy Duck for President-short.*"
ren "Looney Tunes Golden Collection 2 Disc 3 T21*" "The Porky Pig Show  and The Bugs Bunny and Tweety Show - Opening Sequence-other.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T24*" "So Much for So Little-short.*"
ren "Looney Tunes Golden Collection 2 Disc 4 T25*" "Orange Blossoms for Violet-short.*"
rem Volume 3
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T18*" "Whoopi Goldberg-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T22*" "The Bugs Bunny Show - The Honey-Mousers-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 1 T23*" "The Bugs Bunny Show - Ball Point Puns-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T24*" "Sinkin' In The Bathtub-short.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 2 T25*" "It's Got Me Again-short.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T22*" "Porky's Party Storyboard Reel-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T23*" "Point Rationing of Foods-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 3 T24*" "The Bear That Wasn't-other.*"
ren "Looney Tunes Golden Collection Volume 3 Disc 4 T25*" "Falling Hare Storyboard Reel-other.*"
rem Volume 4
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T21*" "Bugs Superstar (Part 1)-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T22*" "Powerhouse in Pictures-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T25*" "The Bugs Bunny Show - Ball Point Puns Bridging Sequences-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T26*" "The Bugs Bunny Show - Foreign Legion Leghorn-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T28*" "Bugs Bunny's Cartoon Carnival Theatrical Trailer-trailer.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 1 T29*" "Bugs Bunny's All-Star Revue Theatrical Trailer-trailer.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T19*" "Bugs Superstar (Part 2)-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T20*" "Porky and Daffy in The William Tell Overture (2006)-short.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T22*" "Little Chic's Wonderful Mother-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 2 T23*" "Tony and Clarence-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T27*" "Porky's Breakdowns-short.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T28*" "Sahara Hare Storyboard Reel-other.*"
ren "Looney Tunes Golden Collection Volume 4 Disc 4 T29*" "Porky's Poor Fish Storyboard Reel-other.*"
rem Volume 5
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T26*" "The Bugs Bunny Show - Bad Time Story-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 1 T27*" "The Bugs Bunny Show - What's Up Dog-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T28*" "The Bashful Buzzard Storyboard Reel-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 3 T29*" "The Bashful Buzzard Original Opening-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T26*" "Bugs and Daffy's Carnival of the Animals-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T27*" "Bugs Bunny's Looney Christmas Tales-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T28*" "Bugs Bunny's Bustin' Out All Over-other.*"
ren "Looney Tunes Golden Collection Volume 5 Disc 4 T32*" "Looney Tunes - Acme Arsenal-trailer.*"
rem Volume 6
rem commentary
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T17*" "Hare Trigger - Commentary by Greg Ford-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T18*" "Birth of a Notion - Commentary by Mark Kausler-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T19*" "My Favorite Duck - Commentary by Jerry Beck-other.*"
rem audio only
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T21*" "Raw Raw Rooster - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T22*" "Jumpin' Jupiter - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T23*" "Rabbit Rampage - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T24*" "Boyhood Daze - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T26*" "Bugs Bunny in King Arthur's Court-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T27*" "Daffy Duck's Easter Egg-Citement-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T29*" "Sniffles Takes a Trip-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T30*" "Hippety Hopper-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T31*" "Rabbit Rampage-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 1 T32*" "Boyhood Daze-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T19*" "Herr Meets Hare - Commentary by Greg Ford-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T20*" "Russian Rhapsody - Commentary by Mark Kausler-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T21*" "Draft Horse - Commentary by Greg Ford-other.*"
rem this doesn't actually have commentary by Jerry Beck.  I've reached out to his to see if there is a version of his commentary available elsewhere
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T22*" "Fifth Column Mouse - Commentary by Jerry Beck-other.*"
rem audio only
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T23*" "Yankee Dood It - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T25*" "Poultry Pirates-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T26*" "A Day At The Beach-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T27*" "The Captain's Christmas-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T28*" "Seal Skinners-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T29*" "Mama's New Hat-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T31*" "The Fighting 69th-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T32*" "Hop and Go-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 2 T33*" "Confusions of a Nutzy Spy-short.*"
rem commentary
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T23*" "Shuffle Off To Buffalo - Commentary by Jerry Beck-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T24*" "A Cartoonist's Nightmare - Commentary by Jerry Beck-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T26*" "The World of Leon Schlesinger - Introduction by Martha Sigall and Jerry Beck-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T30*" "Schlesinger Productions Christmas Party - Commentary by Martha Sigall and Jerry Beck-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T32*" "I Love A Parade-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T33*" "I Like Mountain Music-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T34*" "Sittin' on a Backyard Fence-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 3 T35*" "How Do I know It's Sunday-short.*"
rem commentary
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T23*" "Fresh Airedale - Commentary by Greg Ford-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T24*" "The Hole Idea - Commentary by Mark Kausler-other.*"
rem audio only
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T26*" "The Hole Idea - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T27*" "Martian Through Georgia - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T28*" "Punch Trunk - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T29*" "Wild Wild World - Music-Only-other.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T32*" "Sleep Time Possum-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T33*" "Punch Trunk-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T34*" "Wild Wild World-short.*"
ren "Looney Tunes Golden Collection Volume 6 Disc 4 T35*" "Bartholomew Versus the Wheel-short.*"

rem create all the folders we need and move the extras into them
mkdir 00
move /y *S00* .\00
rem Move comentary files - most of these exist as additional audio tracks on the original short
move /y "Hare Trigger - Commentary by Greg Ford-other.*" .\1945 
move /y "Birth of a Notion - Commentary by Mark Kausler-other.*" .\1947 
move /y "My Favorite Duck - Commentary by Jerry Beck-other.*" .\1942
move /y "Raw Raw Rooster - Music-Only-other.*" .\1956
move /y "Jumpin' Jupiter - Music-Only-other.*" .\1955
move /y "Herr Meets Hare - Commentary by Greg Ford-other.*" .\1945
move /y "Russian Rhapsody - Commentary by Mark Kausler-other.*" .\1944
move /y ""Draft Horse - Commentary by Greg Ford-other.*" .\1942
move /y "Fifth Column Mouse - Commentary by Jerry Beck-other.*" .\1943
move /y "Yankee Dood It - Music-Only-other.*" .\1956
move /y "Shuffle Off To Buffalo - Commentary by Jerry Beck-other.*" .\1933
move /y "A Cartoonist's Nightmare - Commentary by Jerry Beck-other.*" .\1935
move /y "Fresh Airedale - Commentary by Greg Ford-other.*" .\1945
move /y "The Hole Idea - Commentary by Mark Kausler-other.*" .\1955
move /y "The Hole Idea - Music-Only-other.*" .\1955
move /y "Martian Through Georgia - Music-Only-other.*" .\1962

rem deleting the  'play all' files and misc. artifacts
rem Volume 01
del "Looney Tunes Golden Collection Disc 1 T00*"
del "Looney Tunes Golden Collection Disc 1 T20*"
del "Looney Tunes Golden Collection Disc 1 T21*"
del "Looney Tunes Golden Collection Disc 1 T28*"
del "Looney Tunes Golden Collection Disc 2 T00*"
del "Looney Tunes Golden Collection Disc 2 T19*"
del "Looney Tunes Golden Collection Disc 2 T20*"
del "Looney Tunes Golden Collection Disc 2 T21*"
del "Looney Tunes Golden Collection Disc 3 T00*"
del "Looney Tunes Golden Collection Disc 3 T19*"
del "Looney Tunes Golden Collection Disc 3 T20*"
del "Looney Tunes Golden Collection Disc 3 T21*"
del "Looney Tunes Golden Collection Disc 3 T24*"
del "Looney Tunes Golden Collection Disc 4 T00*"
del "Looney Tunes Golden Collection Disc 4 T19*"
del "Looney Tunes Golden Collection Disc 4 T20*"
del "Looney Tunes Golden Collection Disc 4 T21*"
rem Volume 02
del "Looney Tunes Golden Collection 2 Disc 1 T00*"
del "Looney Tunes Golden Collection 2 Disc 1 T16*"
del "Looney Tunes Golden Collection 2 Disc 1 T17*"
del "Looney Tunes Golden Collection 2 Disc 1 T18*"
del "Looney Tunes Golden Collection 2 Disc 2 T00*"
del "Looney Tunes Golden Collection 2 Disc 2 T16*"
del "Looney Tunes Golden Collection 2 Disc 2 T17*"
del "Looney Tunes Golden Collection 2 Disc 3 T00*"
del "Looney Tunes Golden Collection 2 Disc 3 T16*"
del "Looney Tunes Golden Collection 2 Disc 3 T17*"
del "Looney Tunes Golden Collection 2 Disc 3 T18*"
del "Looney Tunes Golden Collection 2 Disc 4 T00*"
del "Looney Tunes Golden Collection 2 Disc 4 T16*"
del "Looney Tunes Golden Collection 2 Disc 4 T17*"
del "Looney Tunes Golden Collection 2 Disc 4 T18*"
del "Looney Tunes Golden Collection 2 Disc 4 T19*"
del "Looney Tunes Golden Collection 2 Disc 4 T23*"
del "Looney Tunes Golden Collection 2 Disc 4 T26*"
rem Volume 03
del "Looney Tunes Golden Collection Volume 3 Disc 1 T00*"
del "Looney Tunes Golden Collection Volume 3 Disc 1 T16*"
del "Looney Tunes Golden Collection Volume 3 Disc 1 T17*"
del "Looney Tunes Golden Collection Volume 3 Disc 1 T21*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T00*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T16*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T17*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T18*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T20*"
del "Looney Tunes Golden Collection Volume 3 Disc 2 T23*"
del "Looney Tunes Golden Collection Volume 3 Disc 3 T00*"
del "Looney Tunes Golden Collection Volume 3 Disc 3 T16*"
del "Looney Tunes Golden Collection Volume 3 Disc 3 T17*"
del "Looney Tunes Golden Collection Volume 3 Disc 3 T18*"
del "Looney Tunes Golden Collection Volume 3 Disc 3 T21*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T00*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T16*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T17*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T18*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T20*"
del "Looney Tunes Golden Collection Volume 3 Disc 4 T24*"
rem Volume 04
del "Looney Tunes Golden Collection Volume 4 Disc 1 T00*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T16*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T17*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T18*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T19*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T24*"
del "Looney Tunes Golden Collection Volume 4 Disc 1 T27*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T00*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T16*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T17*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T18*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T21*"
del "Looney Tunes Golden Collection Volume 4 Disc 2 T24*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T00*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T16*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T17*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T18*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T19*"
del "Looney Tunes Golden Collection Volume 4 Disc 3 T21*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T00*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T16*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T17*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T18*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T19*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T20*"
del "Looney Tunes Golden Collection Volume 4 Disc 4 T26*"
rem Volume 05
del "Looney Tunes Golden Collection Volume 5 Disc 1 T00*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T16*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T17*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T18*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T19*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T20*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T21*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T22*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T23*"
rem the following are individual General Foods commercials.  
rem The 'Play All' version is "Looney Tunes Golden Collection Volume 5 Disc 1 T28-29.*" 
rem renamed "Looney Tunes - S00E44 - Chuck Jones -General Foods commercials starring Bugs and company.*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T29*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T30*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T31*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T32*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T33*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T34*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T35*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T36*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T37*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T38*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T39*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T40*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T41*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T42*"
del "Looney Tunes Golden Collection Volume 5 Disc 1 T43*"
rem
del "Looney Tunes Golden Collection Volume 5 Disc 2 T00*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T16*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T17*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T18*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T19*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T20*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T21*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T22*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T23*"
del "Looney Tunes Golden Collection Volume 5 Disc 2 T27*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T00*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T16*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T17*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T18*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T19*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T20*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T21*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T22*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T24*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T30*"
del "Looney Tunes Golden Collection Volume 5 Disc 3 T33*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T00*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T16*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T17*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T18*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T19*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T20*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T21*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T22*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T25*"
rem Trailers for "Dennis The Menace" and "Smurfs season 1"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T29*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T30*"
del "Looney Tunes Golden Collection Volume 5 Disc 4 T31*"
rem Volume 6
del "Looney Tunes Golden Collection Volume 6 Disc 1 T00*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T16*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T20*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T25*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T28*"
rem Trailers
del "Looney Tunes Golden Collection Volume 6 Disc 1 T33*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T34*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T35*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T36*"
rem
del "Looney Tunes Golden Collection Volume 6 Disc 1 T37*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T38*"
del "Looney Tunes Golden Collection Volume 6 Disc 1 T39*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T00*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T16*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T17*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T18*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T24*"
del "Looney Tunes Golden Collection Volume 6 Disc 2 T30*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T00*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T16*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T17*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T18*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T19*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T20*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T21*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T22*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T25*"
del "Looney Tunes Golden Collection Volume 6 Disc 3 T31*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T00*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T16*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T17*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T18*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T19*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T20*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T21*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T22*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T25*"
del "Looney Tunes Golden Collection Volume 6 Disc 4 T31*"